<?php
/**
 * @file
 * Code for the Bootstrap Jumbotron module
 */

include_once 'hot_bootstrap_jumbotron.features.inc';

/**
 * Implementation of hook_entity_info_alter()
 */
function hot_bootstrap_jumbotron_entity_info_alter(&$entity_info) {
  // Fieldable panel pane bundle to for Bootstrap Jumbotron
  $entity_info['fieldable_panels_pane']['bundles']['hot_bootstrap_jumbotron'] = array(
    'label' => t('Bootstrap Jumbotron'),
    'pane category' => t('HotWidgets!'),
    'pane top level' => FALSE,
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/hot-bootstrap-jumbotron',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}
/**
 * Implements hook_preprocess_fieldable_panels_pane().
 */

function hot_bootstrap_jumbotron_preprocess_fieldable_panels_pane(&$variables){
  if($variables['elements']['#bundle'] === 'hot_bootstrap_jumbotron'){
    $variables['elements']['title'] = array(
      '#theme' => 'html_tag',
      '#tag' => 'h1',
      '#value' => $variables['elements']['#fieldable_panels_pane']->title
    );
  }
}
/**
 * Implements hook_preprocess_panels_pane().
 */
function hot_bootstrap_jumbotron_preprocess_panels_pane(&$variables){
  if(isset($variables['content']['#bundle']) &&  $variables['content']['#bundle']==='hot_bootstrap_jumbotron' ){
    $variables['title'] = null;
  }
}

/**
 * Implements hook_theme().
 */
function hot_bootstrap_jumbotron_theme(){
  return array(
    'fieldable_panels_pane__hot_bootstrap_jumbotron' => array(
      'template' => 'templates/fieldable-panels-pane--hot-bootstrap-jumbotron',
      'render element' => 'elements',
      'type' => 'module'
    )
  );
}
