<?php
/**
 * @file
 * Code for the Bootstrap Jumbotron module
 */

include_once 'hot_bootstrap_jumbotron.features.inc';

/**
 * Implementation of hook_entity_info_alter()
 */
function hot_bootstrap_jumbotron_entity_info_alter(&$entity_info) {
  // Fieldable panel pane bundle to for Bootstrap Jumbotron
  $entity_info['fieldable_panels_pane']['bundles']['hot_bootstrap_jumbotron'] = array(
    'label' => t('Bootstrap Jumbotron'),
    'pane category' => t('HotWidgets!'),
    'pane top level' => FALSE,
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/hot-bootstrap-jumbotron',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}
